### ISSUE TITLE
Remove direct dependency from pundit, only provide adapter module

### ISSUE THREAD

**Issue by markmercedes** [markmercedes/krudmin#25]
* Move pundit inclusion to sample app, the basic gem only should provide an adapter in order to work with pundit.
* The needed logic about the pundit integration belongs in the sample app, the client app is the one that also should install the pundit gem.
* Create documentation page explaining how to use pundit as the authorization library.

**Comment by markmercedes** [comment]
@djavier I beleive we should marry pundit and ride that horse till the end

**Comment by djavier** [comment]
Well no till the end, but lets work around pundit and later we ca go back and rethink this.
