### ISSUE TITLE
Do not allow to destroy sub objects

### ISSUE THREAD

**Issue by djavier** [markmercedes/krudmin#27]
Add a flag for `Krudmin:Fields:HasMany` that does not allow the `_destroy` attribute and no delete button is render on the `_has_many_fields` partial.

**Comment by markmercedes** [comment]
@djavier does this also mean that adding, edditing will be disabled, or is just for deletion?

**Comment by djavier** [comment]
Im dimissing this issue, as this should be handle in the authorization layer rather than the resource.
