### ISSUE TITLE
Relations are not displayed properly in show page

### ISSUE THREAD

**Issue by djavier** [markmercedes/krudmin#31]
Ex.
![image](https://user-images.githubusercontent.com/1663038/34875942-c5ea9766-f775-11e7-8952-bd95766eb59a.png)

**Comment by markmercedes** [comment]
![screen shot 2018-01-15 at 4 40 24 pm](https://user-images.githubusercontent.com/1702736/34960850-0d4418a4-fa13-11e7-9f00-066be5e6f347.png)

👍
